name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu to run the workflow

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your repository's code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker buildx for advanced builds

    - name: Cache Docker layers
      uses: actions/cache@v3  # Updated to v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Get latest version tag
      id: get_version
      run: |
        # Fetch tags from Docker Hub and determine the latest version tag
        TAGS=$(curl -s https://hub.docker.com/v2/repositories/gocho123/my-flask-app/tags/ | jq -r '.results[].name')
        
        # Set the latest version (e.g., v1.2)
        LATEST_TAG=$(echo "$TAGS" | grep -oP 'v[0-9]+\.[0-9]+' | sort -V | tail -n 1)
        
        # Extract the major and minor version numbers
        VERSION=$(echo "$LATEST_TAG" | sed 's/v//')
        MAJOR_MINOR=$(echo "$VERSION" | cut -d. -f1,2)
        
        # Increment the minor version number
        MINOR_VERSION=$(echo "$VERSION" | cut -d. -f2)
        NEXT_MINOR=$((MINOR_VERSION + 1))

        # Construct the new version tag (e.g., v1.3)
        NEXT_TAG="v${MAJOR_MINOR}.${NEXT_MINOR}"
        
        echo "Next version tag: $NEXT_TAG"
        
        echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t gocho123/my-flask-app:${{ github.sha }} .  # Tag with commit SHA
        docker tag gocho123/my-flask-app:${{ github.sha }} gocho123/my-flask-app:latest  # Tag with latest
        docker tag gocho123/my-flask-app:${{ github.sha }} gocho123/my-flask-app:${{ env.NEXT_TAG }}  # New version tag

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password (personal access token) stored in GitHub Secrets

    - name: Push Docker image to Docker Hub
      run: |
        docker push gocho123/my-flask-app:${{ github.sha }}  # Push the image with commit SHA
        docker push gocho123/my-flask-app:latest  # Also push with the 'latest' tag
        docker push gocho123/my-flask-app:${{ env.NEXT_TAG }}  # Push the new version tag (v1.3, v1.4, etc.)
